language: java

jdk:
  - openjdk11

install:
  - wget http://apache.01link.hk//jmeter/binaries/apache-jmeter-5.0.tgz
  - tar -xzvf apache-jmeter-5.0.tgz
  - ./apache-jmeter-5.0/bin/jmeter -n -t src/chapter1/HTTPRequest.jmx

branches:
  only:
    - JMeter5.0