language: java

jdk:
  - openjdk11

install:
  - wget http://apache.01link.hk//jmeter/binaries/apache-jmeter-5.0.tgz
  - tar -xzvf apache-jmeter-5.0.tgz
  - cd ./apache-jmeter-5.0/bin
  - ./jmeter -h

branches:
  only:
    - JMeter5.0